package api

import (
	"database/sql"
	"net/http"

	"github.com/gin-gonic/gin"
	db "github.com/vansh123456/simplebank/db/sqlc"
)

type CreateAccountRequest struct {
	Owner    string `json:"owner" binding:"required"`
	Currency string `json:"currency" binding:"required,oneof= USD EUR"` //we dont allow users to define balance,it will be zero by default
}

func (server *Server) createAccount(ctx *gin.Context) {
	var req CreateAccountRequest
	if err := ctx.ShouldBindJSON(&req); err != nil {

		ctx.JSON(http.StatusBadRequest, errorResponse(err))
		return
	}

	arg := db.CreateAccountParams{
		Owner:    req.Owner,
		Currency: req.Currency,
		Balance:  0,
	}

	account, err := server.store.CreateAccount(ctx, arg)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, errorResponse(err))
		return
	}

	ctx.JSON(http.StatusOK, account)
}

type getAccountRequest struct {
	ID int64 `uri:"id" binding:"required,min=1"`
}

func (server *Server) getAccount(ctx *gin.Context) {
	var req getAccountRequest
	if err := ctx.ShouldBindUri(&req); err != nil { //bind the id with the request url
		ctx.JSON(http.StatusBadRequest, errorResponse(err))
		return
	}
	account, err := server.store.GetAccount(ctx, req.ID)
	if err != nil {
		if err == sql.ErrNoRows { //if the required ID does not exist in the DB
			ctx.JSON(http.StatusNotFound, errorResponse(err))
			return
		}
		ctx.JSON(http.StatusInternalServerError, errorResponse(err)) //any other db errors i
		return
	}
	ctx.JSON(http.StatusOK, account) //normal printing of HTTP res
}

type listAccountRequest struct {
	//form is the type of query params,which we specify in postman,like limiting 1 result per page
	PageID   int64 `form:"page_id" binding:"required,min=1"`
	PageSize int64 `form:"page_size" binding:"required,min=5,max=10"`
}

func (server *Server) listAccount(ctx *gin.Context) {
	var req listAccountRequest
	//this binds the query parameters from the request body which are sent alongwith the request
	if err := ctx.ShouldBindQuery(&req); err != nil { //bind the id with the request url
		ctx.JSON(http.StatusBadRequest, errorResponse(err))
		return
	}

	//listaccparams is AUTOGENERATED BY SQLC,do not edit,it defines all the limits and offsets!
	arg := db.ListAccountsParams{
		Limit:  int32(req.PageSize),
		Offset: int32(req.PageID-1) * int32(req.PageSize),
	}
	accounts, err := server.store.ListAccounts(ctx, arg)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, errorResponse(err)) //any other db errors i
		return
	}
	ctx.JSON(http.StatusOK, accounts) //normal printing of HTTP res
}
